#!/usr/bin/env bash

# Banner
printf "\033[31m"
cat << "EOF"
  &&&&&&&
 &&(*.*)&&
 ___\ /___
(|_     _|)
   )___(
  /     \
 /       \
 `~//~~~\\'
  /_)   (_\
EOF
shopt -s nocasematch
printf "\033[0m"
# Vars
help="""
    D4N155: Tool for smart audit security

    Usage: bash main <option> <target>
    
    Options:
    	-h, --help		Show this mensage.
    	-w, --wordlist		Make the smartwordlist based in informations
				on website.
	-v, --vulners		Get urls that can cause attacks.
	-a, --all		Make all features.

     Target: http(s)://<url>

     It's GNU/GPL version 3
     Project page: https://github.com/Jul10l1r4/D4N155"""
# Functions
#
#

__vul(){
	if [ "$1" ]
	then
		echo "Attacking $1"
	else
		printf "Target is: $1"; read target
	fi
	echo -e "\033[33mYou want update the list Google hacking? (y/n)\033[32m"
	read typed
	case $typed in
		"Yes" | y*)
			echo "Updating database"
			echo "`python3 pagodo/ghdb_scraper.py`"
		;;
		"No" | n*)
			echo "OK ..."
		;;
	esac
	echo "Benning attack using diferents user agents ;)"
	echo "It will to delay..."
	echo "`cd pagodo;python3 pagodo.py -d \"$target\" -l 50 -g google_dorks.txt;cd ..`"
	echo "Finalized attack to $target, see in reports/$target.txt"
}

__wordlist(){
	echo "a"
}

#	Menu
if [ ! "$1" ]
then
	printf "\033[32m"
	PS3="D4N155%#~> "
	select option in "Find vulnerabilities" "Make wordlist"
	do
		case $option in
			"Find vulnerabilities")
				__vul
				;;
			"Make wordlist")
				__wordlist
				;;
			*) echo -e "\033[31mRFTM\033[0m";exit ;;
		esac
	done
	printf "\033[0m"
else
	case "$1" in
	        --h* | "-h")
			echo "$help"
			exit 0
			;;
		--w* | "-w")
			echo "Make the smart wordlist"
			__wordlist
			exit 0	
			;;
		--v* | "-v")
			echo "find to vulners"
			__vul "$2"
			exit 0
			;;
		--a* | "-a")
			echo "full"
			exit 0
			;;
	esac
fi
