#!/usr/bin/env bash

# $1 →  File to delete : Target urls
# $2 →  Report file    : All texts
# $3 →  Wordlist       : Output general
# $4 →  Target
export numberOfUrls="$(cat $1 | wc -l)"
export numberOfContents="$(du -hs $2 | awk '{print $1}')"
export numberOfResult="$(cat $3 | wc -l)"

# Defining name → $4
export name="$(echo $4 | cut -d '.' -f 1)"

# Values
export contentsOfUrls="$(cat $1)"

__make(){
  # Head default of groff
  # https://www.gnu.org/software/groff/manual/groff.html#Page-Layout
  echo """
.TL
Report of $name
.PP
Was processed \fB$numberOfUrls\fP 
urls with \fB$numberOfContents\fP letters, 
resulted in \fB$numberOfResult\fP passwords possibles, based on these
.HnS 1
.HR
.URL https://adasecurity.github.io/D4N155/theories/ operations
.HR
.HnE

Urls analyzed:
.CDS
$contentsOfUrls
.CDE

.PP
\fIGenerated by D4N155\fP

""" | groff -ms -mwww  -T pdf > "../$name.pdf" && \
  ( echo -e "[\e[92m✔\e[m] The file has been saved in\n\e[33m\t→ $name.pdf\e[m" ) || \
  ( echo -e "[\e[31m✘\e[m] groff dont are installed?";exit 2 )
}

# call
__make
